EE = {
        "00" : "No error",
        "01" : "No credit",
        "02" : "Format event due to tag block ID ytes wrong (no match)",
        "03" : "Not MIFARE1k card",
        "04" : "Keycode loading error",
        "05" : "Card communication error",
        "06" : "Mifare authentification error (CRYPTO1 error",
        "07" : "Format event due to tag block checksum wrong",
        "08" : "EEPROM WRITE error (internal)",
        "09" : "No card error (not detected by sensor/ no RF)",
        "0A" : "RS232 CMD error (unknown CMD or arguments/checksum wrong)",
        "0B" : "Dispense limit error/event (flow count overflow or max time exceeded",
        "0C" : "EEPROM write error (external)",
        "0D" : "MFRC chip error",
        "0E" : "Block read error",
        "0F" : "Block write error",
        "10" : "NO_FLOW error (typically when colume < 1 liter after time parameter period",
        "11" : "PROX event (Magnet detected BUT no tag)",
        "12" : "LOW-BATTERY event (battery voltage < low volateg limit parameter)",
        "13" : "PRESSURE event (change in status of water pressure micro-switch",
        "14" : "SuperTap tag/tap TOP-UP complete",
        "15" : "Host VALVE OFF command received and processed (water dispensing terminated)",
        "16" : "START_UP (power-up/reset) event",
        "17" : "NO_FLOW REPEAT error (set if NO_FLOW and tag left in place, cleared by removing tag)",
        "18" : "TAMPER event (change in status of TAmper 1 and / or Tamper 2 switches)",
        "19" : "HEALTH_STATE event (periodic system status report"
        }
