#!/usr/bin/perl
use Cwd;
die "Usage: additem listname name description quantity price\n" unless @ARGV==5;

my( $ln, $n, $d, $q, $p ) = @ARGV;

$ln =~ s/ /%20/g;

# map from pwd of form /homes/USER/public_html/DIRPATH to
# www.doc.ic.ac.uk/~USER/DIRPATH/api
my $pwd = getcwd;
$pwd =~ m|^/homes/(\w+)/public_html/(.*)$|;
my $url="http://www.doc.ic.ac.uk/~$1/$2/api";
#die $url;

my $cmd = qq(curl -X POST -i -d '{"name":"$n", "description": "$d", "quantity": $q, "price": $p}' -H 'Content-Type: application/json' $url/$ln);

#die $cmd;

system( $cmd );
