#!/usr/bin/perl
use Cwd;

die "Usage: mklist owner name\n" unless @ARGV==2;

my( $o, $n ) = @ARGV;

# map from pwd of form /homes/USER/public_html/DIRPATH to
# www.doc.ic.ac.uk/~USER/DIRPATH/api
my $pwd = getcwd;
$pwd =~ m|^/homes/(\w+)/public_html/(.*)$|;
my $url="http://www.doc.ic.ac.uk/~$1/$2/api";
#die $url;

my $cmd = qq(curl -X POST -i -d '{"owner":"$o", "name": "$n"}' -H 'Content-Type: application/json' $url);

#die $cmd;
print $cmd;

system( $cmd );
